# Second stage: Build the server (backend)
FROM node:20 AS server-build

# Add a unprivileged user
RUN groupadd -r cnsp_user && useradd -r -g cnsp_user cnsp_user

# Set working directory for server
WORKDIR /app/server

# Copy server package.json and package-lock.json
COPY ./server/package*.json ./

# Install server dependencies
RUN npm install

# Copy all server source files
COPY ./server .

# Expose port for the server
EXPOSE 3000

# Command to start the backend server
CMD ["npm", "start"]

USER cnsp_user