# First stage: Build the client (frontend)
FROM node:20 AS client-build

# Add a unprivileged user
RUN groupadd -r cnsp_user && useradd -r -g cnsp_user cnsp_user

# Set working directory for client
WORKDIR /app/client

# Copy all client source files
COPY ./client .

# Install client dependencies
RUN npm install

# Build the frontend
RUN npm run build

# Stage 2: Serve the app with Nginx
FROM nginx:alpine

# Remove the default Nginx configuration
RUN rm /etc/nginx/conf.d/default.conf

COPY --from=client-build /app/client/build /usr/share/nginx/html

# Copy a custom Nginx configuration to support HTTPS
COPY ./nginx.conf /etc/nginx/nginx.conf

# Copy the SSL certificates from your repo into the container
COPY ./client/sslcert/nginx-selfsigned.crt /etc/ssl/certs/nginx-selfsigned.crt
COPY ./client/sslcert/nginx-selfsigned.key /etc/ssl/private/nginx-selfsigned.key

# CMD ["npm", "start"]

EXPOSE 80 443

# Containers run nginx with global directives and daemon off
ENTRYPOINT ["nginx", "-g", "daemon off;"]

# Activate User
USER cnsp_user