# First stage: Build the client (frontend)
FROM node:20 AS build-client

# Set working directory for client
WORKDIR /app/client

# Copy client package.json and package-lock.json
COPY ./client/package*.json ./

# Install client dependencies
RUN npm install

# Copy all client source files
COPY ./client ./

# Build the frontend
RUN npm run build

# Command to start the backend server
CMD ["npm", "start"]

EXPOSE 80 443