services:
  # MongoDB service
  mongo:
    image: mongo
    container_name: mongo
    # restart: always
    ports:
      - "27017:27017" # Expose MongoDB on the default port
    volumes:
      - mongodb:/data/db
    environment:
      MONGO_INITDB_DATABASE: calendarDb
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: 1234
    networks:
      - webnet
    command: mongod

  # Node.js server service
  server:
    build:
      context: .
      dockerfile: Dockerfile_server
    container_name: node-app-server
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://mongo:27017/calendarDb
      AUTH: t1Jt4buEdbZk6S7sxXpw4rySPrIcNCUlOhcvoHak2Uc9TSl8LhGhP1BUxmaVrVj
    depends_on:
      - mongo
    networks:
      - webnet

  # Node.js client service
  client:
    build:
      context: .
      dockerfile: Dockerfile_client
    container_name: node-app-client
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - server
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
volumes:
  mongodb: {}
